feature-11 with test and notification
AlexPeppa/learnProject pull request #16
Opened 2024-07-31 16:53 UTC by AlexPeppa

добавил withAxiosServiceErrorHandling , обработка запроса , в HobbyGeneration , для этого произвел рефактор основных  2- х функций получения информации  (generateUser , generateActivity)
добавил тест функции  withAxiosServiceErrorHandling 
добавил компонент ErrorDialogs 
добавил локальное хранение ошибок и ее типы в HobbyGeneration при помощи useState,  чтоб хоть как-то их контролировать
один console.log проглядел )

2024-08-01 12:46 UTC, iligerV requested changes
Так, сделал ты все правильно в части вызова запросов, но нужно новые смыслы в обработку заложить

Сейчас это крайне не гибкая система, более того, она не глобальная и порождает много бойлерплейта

Тут сам решай, как поступать
Если хочешь, можешь настроить хранение для ошибок и закинуть данные в компонент для модалки(у тебя для этого почти все готово)

Или пока ограничиться только нотификацией


Если будешь делать модалки, изучи, как можно организовать единое хранение
Заранее продумай его, порисуй

Подумай, можешь ли ты его сразу для ВСЕХ своих приложений сделать
(Да, ты можешь, но нужно правильно в сторе организовать структуру папок)

2024-08-01 12:46 UTC, iligerV commented on package.json
> +  "jest": { "transformIgnorePatterns": [ "node_modules/(?!axios)" ] }
Это лучше в жест конфиг перенести

2024-08-01 12:46 UTC, iligerV commented on src/containers/utils/handle.ts
> +export const withAxiosServiceErrorHandling = <Response>(
модуль и функцию внутри лучше называть одинаково

Если тут (withAxiosServiceErrorHandling), то и модуль withAxiosServiceErrorHandling.ts

Тест тоже переименуй

2024-08-01 12:46 UTC, iligerV commented on src/containers/HobbyGeneration/models/index.ts
> +export interface RequestError {
Замени на utilityType
Посмотри в доке  тайпскрипта Record

2024-08-01 12:46 UTC, iligerV commented on src/containers/utils/handle.ts
> +          throw new Error(error.message);
Ты должен тут всю логику по выводу модальных окон собирать и вызывать их демонстрацию
В компонентах иначе много дублирования будет - надо переделать

Итого, в компонентах ничего с модальными окнами не делаем
Всю обработку реализуем в catch

2024-08-01 12:46 UTC, iligerV commented on src/containers/HobbyGeneration/index.tsx
> +  const [error, setError] = useState<RequestError>({});
И ты будешь вынужден везде это дублировать - это не правильно
Удаляй всю логику с модальными окнами отсюда

Для простоты пока используй нотификации - их не надо в сторе накапливать

Если хочешь модальные окна использовать, то нужно 
1. сообщения об ошибках хранить в сторе
2. Создать компонент модального окна, который заселектит коллекцию ошибок и по очереди будет их демонстрировать

Можно и что-то другое придумать, но цель у нас одна остается - создать единое место хранения и читать данным одним единственным компонентом

2024-08-01 12:46 UTC, iligerV commented on src/containers/HobbyGeneration/index.tsx
> +    const getUser = () => {
Подход верный, но ты не подумал, что могут быть или будут и другие потребители этого апи внутри твоего приложения

Это значит, что эта функция должна быть в экспортируемым модуле, который в любой момент готов точкой входа поделиться

Сейчас ты ее замкнул внутри функции generateUser, и она никому извне не доступна
Итого, опять потенциальное дублирование)

2024-08-01 12:46 UTC, iligerV commented on src/containers/HobbyGeneration/index.tsx
> +    const getActivity = () => {
Тоже самое

2024-08-01 12:46 UTC, iligerV commented on src/containers/ErrorDialogs/ErrorDialogs.tsx
> +export const ErrorDialogs: React.FC<ErrorProp> = ({ error, deleteError }) => {
Во, это близко к правде

Только ты не должен данные пропсами передавать
Это значит, что у тебя будет куча сторов по всему проекту
И ты не сможешь ее напрямую из экшена тригернуть, так как ошибку нужно будет спустить до компонента

Если этот компонент будет слушать какой-то кусок стора, то она моментально на наличие данных покажет все, что нужно
В стор данные мы можем из любых мест прокинуть, главное иметь возможность dispatch вызвать(это мы можем)

2024-08-01 12:46 UTC, iligerV commented on src/containers/ErrorDialogs/ErrorDialogs.tsx
> +    <React.Fragment>
Фрагмент можно убрать

2024-08-01 12:46 UTC, iligerV commented on src/containers/ErrorDialogs/ErrorDialogs.tsx
> +const Transition = React.forwardRef(function Transition(
Это так анимация настраивает в материал ui?)
Вынеси в отдельный модуль рядом - не мешай вьюхи

2024-08-01 12:46 UTC, iligerV commented on src/containers/ErrorDialogs/ErrorDialogs.tsx
> +import * as React from "react";
Почему опять дублируешь название модуля и папки?

Просто index.tsx пишем

2024-08-01 16:02 UTC, AlexPeppa commented on package.json
> +  "jest": { "transformIgnorePatterns": [ "node_modules/(?!axios)" ] }
+

2024-08-01 16:03 UTC, AlexPeppa commented on package.json
> +  "jest": { "transformIgnorePatterns": [ "node_modules/(?!axios)" ] }
done

2024-08-01 16:04 UTC, AlexPeppa commented on src/containers/utils/handle.ts
> +export const withAxiosServiceErrorHandling = <Response>(
done

2024-08-01 16:09 UTC, AlexPeppa commented on src/containers/ErrorDialogs/ErrorDialogs.tsx
> +    <React.Fragment>
done

2024-08-01 16:11 UTC, AlexPeppa commented on src/containers/ErrorDialogs/ErrorDialogs.tsx
> +import * as React from "react";
done

2024-08-01 16:18 UTC, AlexPeppa commented on src/containers/ErrorDialogs/ErrorDialogs.tsx
> +const Transition = React.forwardRef(function Transition(
done

2024-08-01 16:34 UTC, AlexPeppa commented on src/containers/HobbyGeneration/models/index.ts
> +export interface RequestError {
done

2024-08-02 16:20 UTC, AlexPeppa commented on src/containers/HobbyGeneration/index.tsx
> +    const getActivity = () => {
done

2024-08-02 16:21 UTC, AlexPeppa commented on src/containers/HobbyGeneration/index.tsx
> +    const getUser = () => {
done

2024-08-02 16:21 UTC, AlexPeppa commented on src/containers/HobbyGeneration/index.tsx
> +    const getActivity = () => {
done

2024-08-06 20:28 UTC, iligerV requested changes
Слушай, молодца
Мне все нравится

Давай улучшим селект ошибок для модального и на этом закончим)

2024-08-06 20:28 UTC, iligerV commented on jest.config.js
> +  devDependencies: {
Так, это как сюда попало?)
Все зависимости в пекидж джсоне должны быть

Далее 
`jest: { transformIgnorePatterns: ["node_modules/(?!axios)"] },`
Я помню, что тебя просил перенести эту часть из пекидж джсона 
Наверное, просто ` transformIgnorePatterns: ["node_modules/(?!axios)"] ` должно быть внутри жест конфгиа

2024-08-06 20:28 UTC, iligerV commented on src/index.tsx
> +      <ErrorDialogs />
Молодец, это и правда должно быть на внешнем контуре компонентов)

2024-08-06 20:28 UTC, iligerV commented on src/store/error/reducer.ts
> +export const errorReducer = createReducer(initialState, (builder) => {
Это тоже верно - слой хранения выбрал правильный
Выходит, что у нас один экземпляр хранения ошибок на все приложения(роуты), и все могут им пользоваться

2024-08-06 20:28 UTC, iligerV commented on src/store/error/reducer.ts
> +export const errorReducer = createReducer(initialState, (builder) => {
А почему ты слайс не создал?
С ним будет попроще - не надо будет экшины создавать

Смотри доку
https://redux-toolkit.js.org/api/createSlice

Если есть какие-то смыслы в createReducer, то пиши)

2024-08-06 20:28 UTC, iligerV commented on src/containers/ErrorDialogs/index.tsx
> +  errors: selectors.getErrors(state),
Так, давай переделаем логику работы с коллекцией ошибок

В твоей реализации модалки друг на друга будут наслаиваться и это может быть проблемой, если пользователь уже разбирает сообщение
Ты поверх разбираемой им модалки новую покажешь - это плохо

Напиши еще один селектор, который будет по 0-ому индексу ошибку в компонент передавать
0ой индекс - это первая ошибка, которая попала в коллекцию, то есть мы реализуем очередь

Внутри компонента у тебя будет развилка
1. Селектор отдал существующую ошибку по 0му индексу - показываем модальное окно
2. Селектор вернул undefined, так как коллекция ошибок пустая - рендерим null


Далее, deleteError удаляет в сторе ошибку по 0му индексу
Коллекция сдвигается влево, и на месте 0го индекса теперь новая ошибка, которую селектор затянет в компонент и так до тех пор, пока коллекция не опустеет

2024-08-06 20:28 UTC, iligerV commented on src/containers/ErrorDialogs/index.tsx
> +    <div>
Тут див убирай

2024-08-06 20:28 UTC, iligerV commented on src/containers/ErrorDialogs/index.tsx
> +export default connect<StateProps, null>(mapStateToProps)(ErrorDialogs);
Поменяй на именной экспорт

2024-08-06 20:28 UTC, iligerV commented on src/containers/HobbyGeneration/api/index.ts
> +export const api = {
Это хорошо!

2024-08-06 20:28 UTC, iligerV commented on src/containers/utils/withAxiosServiceErrorHandling.ts
> +          dispatch(addError(error));
Да, теперь все верно
Для всех ошибок отсюда заполняем коллекцию ошибок

2024-08-07 15:51 UTC, iligerV requested changes

2024-08-07 15:51 UTC, iligerV commented on src/containers/ErrorDialogs/index.tsx
> +export const ErrorDialogsWithConnect = connect<StateProps, null>(mapStateToProps)(ErrorDialogs);
Давай иначе сделаем 
`export const ErrorDialogs = connect<StateProps>(mapStateToProps)(ErrorDialogsComponent);`

2024-08-07 15:51 UTC, iligerV commented on src/containers/ErrorDialogs/index.tsx
> +  firstError: Error;
Тут еще undefined может быть для firstError

2024-08-07 15:51 UTC, iligerV commented on src/containers/ErrorDialogs/index.tsx
>    const [open, setOpen] = React.useState(false);
А зачем тебе этот стейт?

Если пришел существующий firstError, то всегда модалку показываем
Это значит, что достаточно в Dialog пропс open всегда true передавать

А наличие или отсутствие модалки ты контролируешь тернаркой 


Есть еще предложение
Можно попробовать избавиться от тернарки
НО
В Dialog open={Boolean(firstError)}
Тогда, если firstError будет undefined, то модалка скроется

2024-08-07 17:45 UTC, iligerV approved these changes

2024-08-07 17:49 UTC, merged