webpack
AlexPeppa/learnProject pull request #17
Opened 2024-09-08 03:38 UTC by AlexPeppa

подключил webpack, почистил зависимости, добавил быструю загрузку, сократил время сборки за счет отдельной проверки ts.

2024-09-08 15:41 UTC, iligerV commented
Ты целый фолдер лишний закомитил)
dist нужно добавить в git ignore, чтобы он, как и нод модули, например, в комиты не попадал

2024-09-08 16:40 UTC, iligerV requested changes
В целом, все не плохо
Нужно кое в чем разобраться, исправить или обосновать

Далее смерджим эту часть и усложним)


Так же подскажи, работает ли твое приложение локально?
Проверял ли роуты?

2024-09-08 16:40 UTC, iligerV commented on image.d.ts
Подобное храни в одном файле, не разделяй все декларации(image.d.ts, styles.d.ts)

global.d.ts можно файлик создать и там все хранить

2024-09-08 16:40 UTC, iligerV commented on package.json
> +    "react-scripts": "^5.0.1",
Это не нужно

https://www.npmjs.com/package/react-scripts

`This package includes scripts and configuration used by [Create React App](https://github.com/facebook/create-react-app).`

2024-09-08 16:40 UTC, iligerV commented on package.json
> +    "test": "react-scripts test --transformIgnorePatterns 'node_modules/(?!axios)/"
Посмотри, как jest вызывает тесты
https://jestjs.io/docs/cli

Сейчас не верно

2024-09-08 16:40 UTC, iligerV commented on package.json
> +    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.15",
Это зачем?

https://www.npmjs.com/package/@pmmmwh/react-refresh-webpack-plugin
```
An EXPERIMENTAL Webpack plugin to enable "Fast Refresh" (also known as Hot Reloading) for React components.

This plugin is not 100% stable. We're hoping to land a v1 release soon - please help us by reporting any issues you've encountered!
```

hot module replacement включен в вебпак дев сервер

https://webpack.js.org/guides/hot-module-replacement/

```
Hot Module Replacement (or HMR) is one of the most useful features offered by webpack. It allows all kinds of modules to be updated at runtime without the need for a full refresh.
```

2024-09-08 16:40 UTC, iligerV commented on package.json
> +    "react-refresh": "^0.14.2",
Вот ты набрал технологий)
От всех авторов по чуть-чуть?

https://www.npmjs.com/package/react-refresh

```
This package implements the wiring necessary to integrate Fast Refresh into bundlers. Fast Refresh is a feature that lets you edit React components in a running application without losing their state. It is similar to an old feature known as "hot reloading", but Fast Refresh is more reliable and officially supported by React.
```

Почему тебе built in hmr внутри вебпака v5 не достаточно?

2024-09-08 16:40 UTC, iligerV commented on package.json
> +    "react-refresh-typescript": "^2.0.9",
https://www.npmjs.com/package/react-refresh-typescript

Тут посмотри, сколько скачиваний вообще 

![image](https://github.com/user-attachments/assets/9df8e832-39fa-4699-a4eb-8b6347d7412b)
Это очень мало


И вот тут, собственно, объяснение чуть ниже

````This package is primarily aimed at developers of bundler plugins````
Промт перевод - Этот пакет в первую очередь предназначен для разработчиков плагинов bundler

Ты уверен, что оно тебе надо?)

2024-09-08 16:40 UTC, iligerV commented on package.json
> +    "typescript-plugin-css-modules": "^5.1.0",
Ты его вообще подключил?

![image](https://github.com/user-attachments/assets/d49f560e-8567-4144-af22-64c3481973ab)


И точно ли он нужен для поддержки типизации?
Обычно я просто css-loader использую

При импорте ключи доступны и подсказки есть

Ты с какой целью этот пакет добавил?

2024-09-08 16:40 UTC, iligerV commented on public/manifest.json
> +      "src": "./oblako.png",
Перепутал наименование?)

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +        options: {
Ты используешь правильный подход в связке ts-loader с "fork-ts-checker-webpack-plugin": "^9.0.2",

Но ты забыл тут включить опцию transpileOnly: true

Это намеренно или случайно?


Если случайно, то разберись, какую задачу мы решаем и донастрой

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +        options: {
Тебе почти удалось меня подловить)
У тебя 9.0.2
````
{
        test: /\.tsx?$/,
        loader: 'ts-loader',
        // add transpileOnly option if you use ts-loader < 9.3.0 
        // options: {
        //   transpileOnly: true
        // }
      }
````

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +              modules: {
Проверь назначение поля и подумай, нужно ли оно тебе
````
modules.localIdentName 
````

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +    new ReactRefreshWebpackPlugin(),
Это под вопросом?
Если расскажешь цель, то готов согласиться)

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +    alias: {
Алиасы всегда через @
@src и тд

Так же их нужно добавить в жест конфиг и ts конфиг

tsConfig смотри поле paths

jestConfig смотри moduleNameMapper

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +    host: "0.0.0.0",
local-ip

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +  devServer: {
Тут только для mode === development
Иначе undefined заполняем

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +  devServer: {
Хотя может на свежих версиях вебпака не надо императивно выключать для билда какие-то фичи
Это нужно проверить


Вообще, идея такая
Для локальной разработки(development) выключаем все минификации и прочее, что уменьшает бандл и тем самым замедляет запуск проекта и hmr

Для билда(production) выключаем все девелоперские фичи типа дев сервера, stats, devtool и прочее
Так же включаем все процессы оптимизации, чтобы бандл уменьшить

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +const config: Configuration = {
Не вижу опции optimization, которая уменьшает бандл

Смотри https://www.npmjs.com/package/terser-webpack-plugin

У меня в таком виде используется

````
  optimization: {
    minimize: true, -> isProduction -> mode === "production"
    minimizer: [
      new TerserPlugin({
        parallel: true,
      }),
    ],
  },
````

2024-09-08 16:40 UTC, iligerV commented on webpack.config.ts
> +const config: Configuration = {
И вот для css пример
Нужно два minimizer'a использовать)

````
  optimization: {
    minimizer: [
      // For webpack@5 you can use the `...` syntax to extend existing minimizers (i.e. `terser-webpack-plugin`), uncomment the next line
      // `...`,
      new CssMinimizerPlugin(),
    ],
  },
  plugins: [new MiniCssExtractPlugin()],
};
````

2024-09-16 03:41 UTC, AlexPeppa commented on webpack.config.ts
> +        options: {
Tip: When you add the [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin) to your webpack config, the transpileOnly will default to true, so you can skip that option.
в документе по ts-loader

2024-09-19 03:12 UTC, AlexPeppa commented on webpack.config.ts
> +module.exports = (env: Env): Configuration => {
There is one change that you will have to make to your webpack config. Typically, module.exports points to the configuration object. To use the env variable, you must convert module.exports to a function:
так в доке написано , и так работает все )

2024-09-19 15:04 UTC, iligerV requested changes
Отлично!

Посмотри еще работу с ассетами и реши, удобнее ли тебе с ними в таким виде будет работать

Потом смерджим)

2024-09-19 15:04 UTC, iligerV commented on dist/index.html
Дист полностью удаляй)

2024-09-19 15:04 UTC, iligerV commented on webpack.config.ts
> +module.exports = (env: Env): Configuration => {
Ааа..прикольно)
Тогда да, лучше через export

2024-09-19 15:04 UTC, iligerV commented on webpack.config.ts
> +        "...",
Ахах...это не надо)))

2024-09-19 15:04 UTC, iligerV commented on webpack.config.ts
> +          test: /\.(jpg|jpeg|png|gif|svg)$/,
Посмотри, что вебпак сегодня предлагает в части ассетов
https://webpack.js.org/guides/asset-modules/
``Asset Modules types replace all of these loaders by adding 4 new module types:``

2024-09-19 15:06 UTC, iligerV commented on webpack.config.ts
> +        options: {
Я выше скидывал объяснение
С этим тоже нужно внимательно

// add transpileOnly option if you use ts-loader < 9.3.0

2024-09-21 13:17 UTC, iligerV approved these changes

2024-09-23 00:29 UTC, merged