unit tests , react testing library
AlexPeppa/learnProject pull request #19
Opened 2024-11-10 19:43 UTC by AlexPeppa

add unit tests , react testing library

2024-11-11 17:59 UTC, iligerV commented on src/containers/Cars/Car/utils/deleteDraftCarModel/index.test.ts
> +  test('should return filter Models', () => {
Так же можно добавить тесты для инпута:

1. deleteDraftCarModel([], 'audi') -> не ломаемся для пустых коллекций
2. deleteDraftCarModel(['bmw'', 'mercedes'], '') -> не ломаемся для пустых моделей
4. deleteDraftCarModel(['bmw'', 'mercedes'], 'audi') -> не ломаемся, если не нашли совпадений

2024-11-11 17:59 UTC, iligerV commented on src/containers/Cars/Car/utils/deleteDraftCarModel/index.ts
> +export const deleteDraftCarModel = (array: string[], model: string) =>
Помни про имена
array - не лучший вариант

2024-11-11 17:59 UTC, iligerV commented on src/containers/Cars/index.test.tsx
> +  test('cars Snapshot test', () => {
Снепшоты в большинстве случаев избыточны, поэтому я их вообще не использую
С ними больше мороки, чем пользы

Ты тут что проверяешь? Я не вижу, что в снепшоте внутри

85%, что этот тест можно удалить вместе с снепшот файлом

2024-11-11 17:59 UTC, iligerV commented on src/containers/Cars/index.test.tsx
> +    expect(createCarCancelBtn).toBeNull();
Ахах...хорошая попытка)

Давай перейдем на использование 

`expect(createCarCancelBtn).not.toBeInTheDocument();`

2024-11-11 17:59 UTC, iligerV commented on src/containers/Cars/index.test.tsx
> +      await screen.findByTestId(generateDataTestId('createCar', 'cancelBtn')),
Я везде квери использую

С файнд как-то больше проблем было

Почему тут его решил заиспользовать?

2024-11-11 17:59 UTC, iligerV commented on src/containers/Cars/index.test.tsx
> +    userEvent.click(carsCreateCarBtn);
Иногда нужно эвейт вызвать для события, чтобы оно завершилось

Далее не приходится эвэйт для элементов писать
Можешь тут тоже попробовать

2024-11-11 17:59 UTC, iligerV commented on src/containers/Cars/index.test.tsx
> +    expect(selectCarLi1).toHaveClass('li select');
Молодец, разобрался)

2024-11-11 17:59 UTC, iligerV commented on src/containers/HobbyGeneration/Statistic/utils/accessibilityAndPriseTotal/index.ts
> +  array.reduce(
Здесь, возможно, потерял тип

`array.reduce<{ accessibilityTotal: number, priceTotal: number }>(....`

Не забывай указывать дженерик тип для reduce

2024-11-11 17:59 UTC, iligerV commented on src/containers/HobbyGeneration/Statistic/utils/accessibilityAndPriseTotal/index.test.ts
> +  test('should return accessibilityTotal and priseTotal', () => {
Нужно больше тестов для разных инпутов

Кейзы сам можешь придумать

2024-11-11 17:59 UTC, iligerV commented on src/containers/MyRouter/index.test.tsx
> +describe('MyRouter', () => {
Ахах...тут прям видно, что с него начал)

2024-11-11 17:59 UTC, iligerV commented on src/containers/utils/generateDataTestId/index.test.tsx
> +const TestComponent = () => {
Это излишне

Функцию generateDataTestId тестируем НЕ в разрезе компонентов, а как обычную тулзу, коей она и является


И тоже разных инпутов в нее накидай
Одного теста в большинстве случаев мало

2024-11-11 17:59 UTC, iligerV commented on src/containers/utils/generateDataTestId/index.tsx
> +  suffix: string = '1',
Это не верно - он не обязательный
Если нет, то айди двусоставным оставляем

2024-11-11 17:59 UTC, iligerV commented on src/store/rickMorty/childs/characters/utils/createHashMapCharacters/index.ts
> +  array.reduce((characters: Record<number, Character>, selectCharacter: Character) => {
Тоже самое - не забывай про тип
Тут он 100% просто Object

array.reduce< Record<number, Character>>((characters, selectCharacter)

Так как мы дженерик указали, то не надобности типизировать аргументы

2024-11-11 17:59 UTC, iligerV commented on src/store/rickMorty/childs/characters/utils/createHashMapCharacters/index.test.ts
> +      {
Вынеси объекты в переменные

const o1, o2, o3

Собери массив из переменных [o1, o2, o3]

И такую же мапу ниже 
{ 
     [o1.id]: o1,
     [o2.id]: o2,
     [o3.id]: o3,
}

2024-11-11 17:59 UTC, iligerV commented on src/store/rickMorty/childs/selectedCharacter/childs/charactersInEpisodes/utils/createCharacterInEpisodeHashMap/index.ts
> +  array.reduce((characters, selectCharacter) => {
Тип

2024-11-11 17:59 UTC, iligerV commented on src/store/rickMorty/childs/selectedCharacter/childs/charactersInEpisodes/utils/getCharacterInEpisodeData/index.test.ts
> +    const response = [
Тоже самое

Не надо собирать справочники

Выносим объекты в переменные и из них собираем коллекции

2024-11-11 17:59 UTC, iligerV commented on src/store/rickMorty/childs/selectedCharacter/childs/reducer.ts
> +    status: 'false',
Тут правда булевый тип в строчном должен быть?

2024-11-12 02:03 UTC, AlexPeppa commented on src/containers/Cars/index.test.tsx
> +    userEvent.click(carsCreateCarBtn);
про await я в процессе понял , что можно только события дождаться )

2024-11-12 02:19 UTC, AlexPeppa commented on src/containers/HobbyGeneration/Statistic/utils/accessibilityAndPriseTotal/index.test.ts
> +  test('should return accessibilityTotal and priseTotal', () => {
ты имеешь ввиду для кнопок с получением информации тесты ?
инпутов как таковых нет , пользователь сам ничего не вводит .

2024-11-12 02:20 UTC, AlexPeppa commented on src/containers/MyRouter/index.test.tsx
> +describe('MyRouter', () => {
даа это начало)

2024-11-12 04:05 UTC, AlexPeppa commented on src/containers/utils/generateDataTestId/index.tsx
> +  suffix: string = '1',
+

2024-11-12 04:05 UTC, AlexPeppa commented on src/containers/utils/generateDataTestId/index.tsx
> +  suffix: string = '1',
+

2024-11-12 04:09 UTC, AlexPeppa commented on src/containers/utils/generateDataTestId/index.tsx
> +  suffix: string = '1',
✅

2024-11-12 04:09 UTC, AlexPeppa commented on src/containers/utils/generateDataTestId/index.test.tsx
> +const TestComponent = () => {
✅

2024-11-12 04:10 UTC, AlexPeppa commented on src/containers/Cars/Car/utils/deleteDraftCarModel/index.ts
> +export const deleteDraftCarModel = (array: string[], model: string) =>
✅

2024-11-12 04:10 UTC, AlexPeppa commented on src/containers/Cars/index.test.tsx
> +  test('cars Snapshot test', () => {
✅

2024-11-12 04:10 UTC, AlexPeppa commented on src/containers/Cars/index.test.tsx
> +    expect(createCarCancelBtn).toBeNull();
✅

2024-11-12 04:10 UTC, AlexPeppa commented on src/containers/Cars/index.test.tsx
> +      await screen.findByTestId(generateDataTestId('createCar', 'cancelBtn')),
✅

2024-11-12 04:10 UTC, AlexPeppa commented on src/containers/Cars/index.test.tsx
> +    userEvent.click(carsCreateCarBtn);
✅

2024-11-12 04:10 UTC, AlexPeppa commented on src/containers/HobbyGeneration/Statistic/utils/accessibilityAndPriseTotal/index.ts
> +  array.reduce(
✅

2024-11-12 04:16 UTC, AlexPeppa commented on src/store/rickMorty/childs/characters/utils/createHashMapCharacters/index.ts
> +  array.reduce((characters: Record<number, Character>, selectCharacter: Character) => {
✅

2024-11-12 04:21 UTC, AlexPeppa commented on src/store/rickMorty/childs/characters/utils/createHashMapCharacters/index.test.ts
> +      {
✅

2024-11-12 10:48 UTC, AlexPeppa commented on src/store/rickMorty/childs/selectedCharacter/childs/charactersInEpisodes/utils/createCharacterInEpisodeHashMap/index.ts
> +  array.reduce((characters, selectCharacter) => {
у меня 2 абсолютно одинаковые функции по созданию HashMap , есть смысл сделать из них одну ? 
положить на уровень первого компонента, который её использует .
![2 функции ](https://github.com/user-attachments/assets/4f5dacea-6297-4a91-85a6-781fe71cc4b6)

2024-11-12 10:58 UTC, AlexPeppa commented on src/containers/Cars/Car/utils/deleteDraftCarModel/index.test.ts
> +  test('should return filter Models', () => {
export const deleteDraftCarModel = (models: string[], model: string) =>
  models.filter((mark) => mark !== model);
  
  в эту функцию я не могу передать ту модель которой нет в массиве , 
  и не могу удалить элемент если он отсутствует , удаляю из предложенных

  могу удалить единственный элемент -> не ломается

2024-11-12 11:04 UTC, AlexPeppa commented on src/store/rickMorty/childs/selectedCharacter/childs/charactersInEpisodes/utils/getCharacterInEpisodeData/index.test.ts
> +    const response = [
✅

2024-11-13 00:56 UTC, AlexPeppa commented on src/containers/Cars/Car/utils/deleteDraftCarModel/index.test.ts
> +  test('should return filter Models', () => {
✅

2024-11-13 03:13 UTC, AlexPeppa commented on src/store/rickMorty/childs/selectedCharacter/childs/reducer.ts
> +    status: 'false',
✅ там строка status:'dead' такого типа

2024-11-23 16:25 UTC, iligerV commented on src/containers/HobbyGeneration/Statistic/utils/accessibilityAndPriseTotal/index.test.ts
> +  test('should return accessibilityTotal and priseTotal', () => {
Инпут - это ввод
То есть аргументы в твоей функции

2024-11-23 16:25 UTC, iligerV commented on src/containers/Cars/Car/utils/deleteDraftCarModel/index.test.ts
> +    expect(deleteDraftCarModel(['audi'], 'audi')).toEqual([]);
Для каждого expect отдельный test с описание того, что тестируется

Тест не должен при возможности проверять сразу все)
Тут прям явно видно, что все экспекты нужно разделить

2024-11-23 16:25 UTC, iligerV commented on src/containers/Cars/Car/utils/deleteDraftCarModel/index.test.ts
> +    expect(deleteDraftCarModel(models, '')).toEqual(models);
Например,
test('should return non modified models collection for model = empty string', () => {
   expect(deleteDraftCarModel(models, '')).toEqual(models);
})

2024-11-23 16:25 UTC, iligerV commented on src/containers/HobbyGeneration/Statistic/utils/accessibilityAndPriseTotal/index.test.ts
> +  test('should return accessibilityTotal and priseTotal with  undefined information', () => {
У тебя название не отвечает сути теста - ты не возвращаешь undefined

Ex:
should be able to return result for accessibility = undefined & price = undefined 

И может ли accessibilityTotal быть больше 100? Или все-таки это баг?

2024-11-23 16:25 UTC, iligerV commented on src/containers/RickMorty/index.test.tsx
> +  test('should render after action', async () => {
Ты умудрился все в один тест уложить - это не правильно)

Раздели все на отдельные тесты, после этого по существу посмотрю, что внутри происходит

Каждый тест отдельный пользовательский сценарий проверяет
У него есть начало и конец, шагов не должно быть много


Если этот тест поломается, то толком не будет понятно, что пошло не так

2024-11-23 16:25 UTC, iligerV commented on src/store/rickMorty/childs/characters/utils/createHashMapFromArray/index.test.ts
> +describe('createHashMapCharacter', () => {
Этот тест можно удалить)

Ты должен один тест написать для arrayToMap

Для реализаций тесты писать не нужно)

2024-11-23 16:25 UTC, iligerV commented on src/store/rickMorty/childs/characters/utils/createHashMapFromArray/index.ts
> +export const arrayToMap = <T>(array: T[], keyName: string) =>
Эта функция не должна быть в сторе
тем более в части рика и морти

Она должны быть в общих тулзах

src.utils

2024-11-23 16:25 UTC, iligerV commented on src/store/rickMorty/childs/characters/utils/createHashMapFromArray/index.ts
> +export const arrayToMap = <T>(array: T[], keyName: string) =>
Еще можно тип немного улучшить

```
export const arrayToMap = <T extends Object>(array: T[], keyName: keyof T) => {
  return array.reduce<Record<ReactText, T>>((dictionary, next) => {
    const key = next[keyName] as ReactText;
    dictionary[key] = next;
    return dictionary;
  }, {});

1. <T extends Object> -> Теперь внутри array только объекты будем ожидать, иначе(например, массив строк) ошибка
2. keyName: keyof T -> сможем передать только те ключи, которые находятся внутри передаваемой коллекции объектов. Тс тоже начнет их подсказывать
3. array.reduce<Record<ReactText, T>> -> теперь и строки тоже могут быть ключами твоей мапы
4. const key = next[keyName] as ReactText; -> это небольшое упрощение типизации. Так как next[keyName] может не только строки содержать, а, например, null | undefined | функции и тд, то мы действительно такие ключи использовать не можем. Поэтому мы кастим тут тип в string | number, рассчитывая, что разработчик не дурак) Если этого не сделать, то нужно было бы тайп гварды устанавливать.
```

2024-11-25 01:35 UTC, AlexPeppa commented on src/containers/HobbyGeneration/Statistic/utils/accessibilityAndPriseTotal/index.test.ts
> +  test('should return accessibilityTotal and priseTotal with  undefined information', () => {
accessibilityTotal может быть больше 100 , если у меня 1000 пользователей и у каждого  accessibility =0.2
а вот accessibility не может быть больше 1 , но я не делаю эту проверку , данные с сервера на корректность не проверяю

2024-12-17 12:20 UTC, iligerV requested changes

2024-12-17 12:20 UTC, iligerV commented on src/containers/RickMorty/index.test.tsx
> +    const state: Partial<AppStore> = {
Это правильно, но генерация не верная)
Что ты будешь делать, если твой стор будет на порядки больше?)

У тебя уже есть на проекте инициализация стора, ты ее используешь, когда в Provider закидываешь дефолтное состония
Здесь нужно сделать тоже самое - создать дефолт

Далее ты меняешь только те части стора, которые должны измениться
Используем для этого расширение объекта

```
{
    ...defaultStoreState,
             rickAndMorty: {
                     ...defaultStoreState.rickAndMorty,
                     status: ApiReqeustState.SUCCESS
              }
}
```

2024-12-17 12:20 UTC, iligerV commented on src/mocks/handlers.ts
> +  http.get('https://rickandmortyapi.com/api/episode/1', () =>
500 ошибки не тестировал?
Для этого мы должны внутри теста заоверайдить хендлер внутри test

```
test(smth, () => {
            server.use(
                   http.get('https://rickandmortyapi.com/api/episode/1', () => ...и  тут тело ошибки
           )

Далее после рендера апишка вернет ответ ошибки и нужно проверить, что компонент отработал адекватно
}
```

При этом да, в нашим mocks/handlers всегда 200 должны лежать
Мало ли, в каких тестах они еще пригодятся - не придется их каждый раз описывать
А ошибка это частный случай

2026-02-08 14:10 UTC, merged